import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { GlobalProvider } from "./_redux/provider";

const font = localFont({
  src: "../public/fonts/HiraginoKakuGothicProN.otf",
  weight: "600",
});

export const metadata: Metadata = {
  title: "Super real",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <main className="tw-min-h-screen">
          <GlobalProvider>{children}</GlobalProvider>
        </main>
      </body>
    </html>
  );
}
